{% set name = "pyxstruct" %}
{% set version = "1.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b81c141c8fe66a4549e79c6ba167c780ec8ffc4fd493896751ce65eed6494669

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - matplotlib
    - numpy
    - pandas
    - pip
    - python
    - seaborn
  run:
    - matplotlib
    - numpy
    - pandas
    - python
    - seaborn

test:
  imports:
    - pyxstruct

about:
  home: https://github.com/bobbypaton/pyX-Struct
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt 
  summary: Scrape Geometric X-ray Data from the Cambridge Structural Database
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - bobbypaton
